### ISSUE TITLE
GPL3?

### ISSUE THREAD

**Issue by drmikecrowe** [omarabid/WordPress-Plugin-Boilerplate#2]
By making the license of this GPL3, are you forcing all plugins derived from this as GPL3 as well?

**Comment by omarabid** [comment]
Yes. Is that a problem for you?

**Comment by drmikecrowe** [comment]
I think so.  Isn't GPL3 more restrictive than the GPL2 that Wordpress uses?

Ideally, if this is really a tool for developers, I expected the license to
be a stub that would be left to the developer's choice.

**Comment by omarabid** [comment]
Wasn't really aware of that! Changed the License to GPL 2.
